In [1]:
from sklearn.linear_model import SGDRegressor

sgdmodel = SGDRegressor(penalty='l2') # L2 regularization

In [14]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

iris = datasets.load_iris()

print(iris["data"])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [17]:
IRIS_VIRGINICA = 2

X = iris["data"][:, (2, 3)] # X = columns 2 and 3 of iris["data"]; They correspond to petal length, petal width
y = (iris["target"] == IRIS_VIRGINICA).astype(np.float64) # same as np.array([(y_i == IRIS_VIRGINICA) for y_i in iris["target"]]).astype(np.float64)

specificity = 1

svm_clf = Pipeline([
    ("scaler", StandardScaler()),
    ("linear_svc", LinearSVC(C=specificity, loss='hinge')) # alternatively, SVC(kernel="linear", C=specificity)
])

svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [19]:
svm_clf.predict([[2.25, 4.7]])

array([1.])

In [22]:
from sklearn.svm import SVC

# linear kernel
linear_kernel_svc = Pipeline([
    ("scaler", StandardScaler()),
    ("svc_clf", SVC(kernel="linear", C=specificity))
])

# polynomial kernel
polynomial_kernel_svc = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="poly", degree=3, coef0=1, C=specificity))
])

In [24]:
# Gaussian RBF similarity features
radial_basis_function_kernel_svc = Pipeline([
    ("scaler", StandardScaler()),
    ("svm_clf", SVC(kernel="rbf", gamma=3, C=specificity))
])

radial_basis_function_kernel_svc.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()), ('svm_clf', SVC(C=1, gamma=3))])

In [25]:
from sklearn.svm import SVR, LinearSVR

svm_regression = LinearSVR(epsilon=3) # epsilon = street width
svm_polynomial_regression = SVR(kernel="poly", degree=2, C=50, epsilon=0.5)

svm_regression.fit(X, y)
svm_polynomial_regression.fit(X, y)

SVR(C=50, degree=2, epsilon=0.5, kernel='poly')